echo "--- Node.js ---"; node -v 2>/dev/null || echo "LIPSA"
echo "--- npm ---"; npm -v 2>/dev/null || echo "LIPSA"
echo "--- pnpm ---"; pnpm -v 2>/dev/null || echo "LIPSA"
echo "--- corepack ---"; corepack --version 2>/dev/null || echo "LIPSA"
echo "--- git ---"; git --version 2>/dev/null || echo "LIPSA"
echo "--- git user.name ---"; git config --global user.name 2>/dev/null || echo "NESETAT"
echo "--- git user.email ---"; git config --global user.email 2>/dev/null || echo "NESETAT"
echo "--- gh CLI ---"; gh --version 2>/dev/null || echo "LIPSA"
echo "--- gh auth status ---"; gh auth status 2>&1 || echo "NEAUTENTIFICAT"
echo "--- VS Code CLI (din WSL) ---"; code --version 2>/dev/null || echo "LIPSA / nu e in PATH din WSL"
