import { neon } from '@neondatabase/serverless';
import { SUPPORTED_METRIC_KEYS, type MetricKey, type MetricValueMap } from '../types';

const CREATE_ETF_HISTORY_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS etf_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    report_date TEXT NOT NULL,
    report_url TEXT,
    created_at TEXT NOT NULL
);
`;

const CREATE_ETF_METRICS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS etf_metrics (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    history_id INTEGER NOT NULL REFERENCES etf_history(id) ON DELETE CASCADE,
    metric_key TEXT NOT NULL,
    metric_value DOUBLE PRECISION,
    created_at TEXT NOT NULL,
    UNIQUE(history_id, metric_key)
);
`;

const CREATE_SYNC_RUNS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS sync_runs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    status TEXT NOT NULL
);
`;

const CREATE_MONITORED_ETFS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS monitored_etfs (
    symbol TEXT PRIMARY KEY,
    enabled INTEGER NOT NULL
);
`;

const CREATE_MONITORED_FIELDS_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS monitored_fields (
    field_name TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    enabled INTEGER NOT NULL
);
`;

const CREATE_CONFIGURATION_TABLE_SQL = `
CREATE TABLE IF NOT EXISTS configuration (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
`;

const DELETE_DUPLICATE_HISTORY_SQL = `
DELETE FROM etf_history older
USING etf_history newer
WHERE older.symbol = newer.symbol
  AND older.report_date = newer.report_date
  AND older.id < newer.id;
`;

const CREATE_HISTORY_UNIQUE_INDEX_SQL = `
CREATE UNIQUE INDEX IF NOT EXISTS idx_history_symbol_date
ON etf_history(symbol, report_date);
`;

const CREATE_HISTORY_LOOKUP_INDEX_SQL = `
CREATE INDEX IF NOT EXISTS idx_history_symbol_date_id
ON etf_history(symbol, report_date DESC, id DESC);
`;

const CREATE_ETF_METRICS_LOOKUP_INDEX_SQL = `
CREATE INDEX IF NOT EXISTS idx_etf_metrics_metric_history
ON etf_metrics(metric_key, history_id);
`;

const METRIC_KEY_SET = new Set<string>(SUPPORTED_METRIC_KEYS);

const DEFAULT_MONITORED_ETFS = [
  'TVBETETF',
  'PTENGETF',
  'BTBETRETF',
  'BKBETETF',
  'GIBEFETF',
  'GIBXTETF',
] as const;

const DEFAULT_MONITORED_FIELDS = [
  {
    fieldName: 'units_in_circulation',
    displayName: 'Units in Circulation',
    enabled: 1,
  },
  {
    fieldName: 'vuan',
    displayName: 'VUAN',
    enabled: 1,
  },
  {
    fieldName: 'net_assets',
    displayName: 'Net Assets',
    enabled: 1,
  },
] as const;

const DEFAULT_CONFIGURATION = [
  { key: 'scheduler_enabled', value: 'true' },
  { key: 'scheduler_time', value: '09:00' },
  { key: 'dashboard_metric', value: 'units_in_circulation' },
] as const;

interface UpsertHistoryEntry {
  symbol: string;
  reportDate: Date;
  metrics: MetricValueMap;
  reportUrl: string;
}

interface EtfHistoryRecordRow {
  id: number | string;
  symbol: string;
  report_date: string;
  report_url: string | null;
  created_at: string;
}

interface EtfHistoryMetricJoinRow extends EtfHistoryRecordRow {
  metric_key: string | null;
  metric_value: number | null;
}

interface EtfHistoryRow {
  id: number;
  symbol: string;
  report_date: string;
  units_in_circulation: number | null;
  vuan: number | null;
  net_assets: number | null;
  report_url: string | null;
  created_at: string;
}

interface EtfHistoryWithDeltaRow extends EtfHistoryRow {
  previous_units_in_circulation: number | null;
  previous_vuan: number | null;
  previous_net_assets: number | null;
}

interface SyncOverview {
  status: 'Completed' | 'Running' | 'Failed';
  completedAt: string | null;
  durationSeconds: number | null;
}

type NeonDatabase = ReturnType<typeof neon>;

export class DatabaseService {
  private static initializationPromise: Promise<void> | null = null;
  private readonly database: NeonDatabase;

  constructor() {
    const databaseUrl = process.env.DATABASE_URL;
    if (!databaseUrl) {
      throw new Error('DATABASE_URL is not set');
    }

    this.database = neon(databaseUrl);

    if (!DatabaseService.initializationPromise) {
      DatabaseService.initializationPromise = this.initializeDatabase().catch((error: unknown) => {
        DatabaseService.initializationPromise = null;
        throw error;
      });
    }
  }

  getDatabase(): NeonDatabase {
    const database = this.database;
    return (async (query: string, params?: unknown[]) => {
      await this.ensureInitialized();
      return database(query, params);
    }) as unknown as NeonDatabase;
  }

  async insertHistory(entry: UpsertHistoryEntry): Promise<void> {
    await this.ensureInitialized();

    const createdAt = new Date().toISOString();
    const reportDateIso = entry.reportDate.toISOString();
    const rows = (await this.database(
      `
      INSERT INTO etf_history (
        symbol,
        report_date,
        report_url,
        created_at
      ) VALUES ($1, $2, $3, $4)
      RETURNING id
      `,
      [entry.symbol, reportDateIso, entry.reportUrl, createdAt],
    )) as Array<{ id: number | string }>;

    const historyId = Number(rows[0]?.id);
    if (!Number.isFinite(historyId)) {
      throw new Error('Failed to insert history row');
    }

    await this.upsertMetricValues(historyId, entry.metrics, createdAt);

    console.log({
      action: 'insert',
      symbol: entry.symbol,
      reportDate: entry.reportDate,
      changes: 1,
      lastInsertRowid: historyId,
      createdAt,
    });
  }

  async updateHistory(entry: UpsertHistoryEntry): Promise<void> {
    await this.ensureInitialized();

    const reportDateKey = entry.reportDate.toISOString().substring(0, 10);
    const createdAt = new Date().toISOString();
    const rows = (await this.database(
      `
      UPDATE etf_history
      SET
          report_url = $1,
          created_at = $2
      WHERE
          symbol = $3
      AND
          LEFT(report_date, 10) = $4
      RETURNING id
      `,
      [entry.reportUrl, createdAt, entry.symbol, reportDateKey],
    )) as Array<{ id: number | string }>;

    const historyId = Number(rows[0]?.id);
    if (!Number.isFinite(historyId)) {
      return;
    }

    await this.upsertMetricValues(historyId, entry.metrics, createdAt);
  }

  async getLatestHistory(symbol: string): Promise<EtfHistoryRow | null> {
    await this.ensureInitialized();

    const rows = (await this.database(
      `
      SELECT
        h.id,
        h.symbol,
        h.report_date,
        h.report_url,
        h.created_at,
        m.metric_key,
        m.metric_value
      FROM etf_history h
      LEFT JOIN etf_metrics m ON m.history_id = h.id
      WHERE h.id = (
          SELECT id
          FROM etf_history
          WHERE symbol = $1
          ORDER BY report_date DESC, id DESC
          LIMIT 1
      )
      ORDER BY h.id, m.metric_key
      `,
      [symbol],
    )) as EtfHistoryMetricJoinRow[];

    if (rows.length === 0) {
      return null;
    }

    return this.mapHistoryMetricRows(rows)[0] ?? null;
  }

  async getHistoryForReportDate(symbol: string, reportDate: Date): Promise<EtfHistoryRecordRow | null> {
    await this.ensureInitialized();

    const reportDateKey = reportDate.toISOString().substring(0, 10);
    const rows = (await this.database(
      `
      SELECT
        id,
        symbol,
        report_date,
        report_url,
        created_at
      FROM etf_history
      WHERE symbol = $1 AND LEFT(report_date, 10) = $2
      ORDER BY report_date DESC, id DESC
      LIMIT 1
      `,
      [symbol, reportDateKey],
    )) as EtfHistoryRecordRow[];

    return rows[0] ?? null;
  }

  async getHistory(limit = 100): Promise<EtfHistoryRow[]> {
    await this.ensureInitialized();

    const rows = (await this.database(
      `
      SELECT
        h.id,
        h.symbol,
        h.report_date,
        h.report_url,
        h.created_at,
        m.metric_key,
        m.metric_value
      FROM etf_history h
      LEFT JOIN etf_metrics m ON m.history_id = h.id
      WHERE h.id IN (
          SELECT id
          FROM etf_history
          ORDER BY report_date DESC, symbol ASC, id DESC
          LIMIT $1
      )
      ORDER BY h.report_date DESC, h.symbol ASC, h.id DESC, m.metric_key ASC
      `,
      [limit],
    )) as EtfHistoryMetricJoinRow[];

    return this.mapHistoryMetricRows(rows);
  }

  async getLatestHistoryForAll(): Promise<EtfHistoryRow[]> {
    await this.ensureInitialized();

    const rows = (await this.database(
      `
      SELECT
        h.id,
        h.symbol,
        h.report_date,
        h.report_url,
        h.created_at,
        m.metric_key,
        m.metric_value
      FROM etf_history h
      LEFT JOIN etf_metrics m ON m.history_id = h.id
      WHERE h.id = (
          SELECT id
          FROM etf_history
          WHERE symbol = h.symbol
          ORDER BY report_date DESC, id DESC
          LIMIT 1
      )
      ORDER BY h.symbol, m.metric_key
      `,
    )) as EtfHistoryMetricJoinRow[];

    return this.mapHistoryMetricRows(rows);
  }

  async getLatestHistoryWithPrevious(): Promise<EtfHistoryWithDeltaRow[]> {
    await this.ensureInitialized();

    const latestMetricRows = (await this.database(
      `
      SELECT
        h.id,
        h.symbol,
        h.report_date,
        h.report_url,
        h.created_at,
        metric.metric_key,
        metric.metric_value
      FROM etf_history h
      INNER JOIN monitored_etfs monitored ON monitored.symbol = h.symbol
      LEFT JOIN etf_metrics metric ON metric.history_id = h.id
      WHERE h.id = (
          SELECT id
          FROM etf_history
          WHERE symbol = h.symbol
          ORDER BY report_date DESC, id DESC
          LIMIT 1
      )
      AND monitored.enabled = 1
      ORDER BY monitored.symbol, metric.metric_key
      `,
    )) as EtfHistoryMetricJoinRow[];

    const latestRows = this.mapHistoryMetricRows(latestMetricRows);
    const previousMetricStatement = `
      SELECT metric.metric_value
      FROM etf_history history
      INNER JOIN etf_metrics metric ON metric.history_id = history.id
      WHERE history.symbol = $1
        AND history.id <> $2
        AND metric.metric_key = $3
        AND metric.metric_value IS NOT NULL
      ORDER BY history.report_date DESC, history.id DESC
      LIMIT 1
    `;

    const result: EtfHistoryWithDeltaRow[] = [];
    for (const latestRow of latestRows) {
      const previousMetricValues = this.createEmptyMetricValueMap();

      for (const metricKey of SUPPORTED_METRIC_KEYS) {
        const previousMetricRows = (await this.database(
          previousMetricStatement,
          [latestRow.symbol, latestRow.id, metricKey],
        )) as Array<{ metric_value: number | null }>;

        previousMetricValues[metricKey] = previousMetricRows[0]?.metric_value ?? null;
      }

      result.push({
        id: latestRow.id,
        symbol: latestRow.symbol,
        report_date: latestRow.report_date,
        units_in_circulation: latestRow.units_in_circulation,
        previous_units_in_circulation: previousMetricValues.units_in_circulation,
        vuan: latestRow.vuan,
        previous_vuan: previousMetricValues.vuan,
        net_assets: latestRow.net_assets,
        previous_net_assets: previousMetricValues.net_assets,
        report_url: latestRow.report_url,
        created_at: latestRow.created_at,
      });
    }

    return result;
  }

  async createSyncRun(): Promise<number> {
    await this.ensureInitialized();

    const rows = (await this.database(
      `
      INSERT INTO sync_runs (started_at, status)
      VALUES ($1, $2)
      RETURNING id
      `,
      [new Date().toISOString(), 'running'],
    )) as Array<{ id: number | string }>;

    const id = Number(rows[0]?.id);
    if (!Number.isFinite(id)) {
      throw new Error('Failed to create sync run');
    }

    return id;
  }

  async markSyncRunCompleted(id: number): Promise<void> {
    await this.ensureInitialized();

    await this.database(
      `
      UPDATE sync_runs
      SET completed_at = $1, status = $2
      WHERE id = $3
      `,
      [new Date().toISOString(), 'completed', id],
    );
  }

  async markSyncRunFailed(id: number): Promise<void> {
    await this.ensureInitialized();

    await this.database(
      `
      UPDATE sync_runs
      SET completed_at = $1, status = $2
      WHERE id = $3
      `,
      [new Date().toISOString(), 'failed', id],
    );
  }

  async getSyncOverview(): Promise<SyncOverview> {
    await this.ensureInitialized();

    const latestRunRows = (await this.database(
      `
      SELECT status
      FROM sync_runs
      ORDER BY started_at DESC, id DESC
      LIMIT 1
      `,
    )) as Array<{ status: string }>;

    const latestCompletedRows = (await this.database(
      `
      SELECT started_at, completed_at
      FROM sync_runs
      WHERE status = $1 AND completed_at IS NOT NULL
      ORDER BY completed_at DESC, id DESC
      LIMIT 1
      `,
      ['completed'],
    )) as Array<{ started_at: string; completed_at: string }>;

    const latestRun = latestRunRows[0];
    const latestCompleted = latestCompletedRows[0];

    let status: SyncOverview['status'] = 'Failed';
    if (latestRun?.status === 'completed') {
      status = 'Completed';
    } else if (latestRun?.status === 'running') {
      status = 'Running';
    }

    const durationSeconds =
      latestCompleted &&
      !Number.isNaN(new Date(latestCompleted.started_at).getTime()) &&
      !Number.isNaN(new Date(latestCompleted.completed_at).getTime())
        ? (new Date(latestCompleted.completed_at).getTime() -
            new Date(latestCompleted.started_at).getTime()) /
          1000
        : null;

    return {
      status,
      completedAt: latestCompleted?.completed_at ?? null,
      durationSeconds,
    };
  }

  private async ensureInitialized(): Promise<void> {
    if (DatabaseService.initializationPromise) {
      await DatabaseService.initializationPromise;
    }
  }

  private async initializeDatabase(): Promise<void> {
    await this.database(CREATE_ETF_HISTORY_TABLE_SQL);
    await this.database(CREATE_ETF_METRICS_TABLE_SQL);
    await this.database(CREATE_SYNC_RUNS_TABLE_SQL);
    await this.database(CREATE_MONITORED_ETFS_TABLE_SQL);
    await this.database(CREATE_MONITORED_FIELDS_TABLE_SQL);
    await this.database(CREATE_CONFIGURATION_TABLE_SQL);
    await this.runHistoryDeduplicationMigration();
    await this.runLookupIndexesMigration();
    await this.seedDefaultMonitoredEtfs();
    await this.seedDefaultMonitoredFields();
    await this.seedDefaultConfiguration();
  }

  private async runHistoryDeduplicationMigration(): Promise<void> {
    await this.database(DELETE_DUPLICATE_HISTORY_SQL);
    await this.database(CREATE_HISTORY_UNIQUE_INDEX_SQL);
  }

  private async runLookupIndexesMigration(): Promise<void> {
    await this.database(CREATE_HISTORY_LOOKUP_INDEX_SQL);
    await this.database(CREATE_ETF_METRICS_LOOKUP_INDEX_SQL);
  }

  private async seedDefaultMonitoredEtfs(): Promise<void> {
    for (const symbol of DEFAULT_MONITORED_ETFS) {
      await this.database(
        `
        INSERT INTO monitored_etfs (symbol, enabled)
        VALUES ($1, $2)
        ON CONFLICT (symbol) DO NOTHING
        `,
        [symbol, 1],
      );
    }
  }

  private async seedDefaultMonitoredFields(): Promise<void> {
    for (const field of DEFAULT_MONITORED_FIELDS) {
      await this.database(
        `
        INSERT INTO monitored_fields (field_name, display_name, enabled)
        VALUES ($1, $2, $3)
        ON CONFLICT (field_name) DO NOTHING
        `,
        [field.fieldName, field.displayName, field.enabled],
      );
    }
  }

  private async seedDefaultConfiguration(): Promise<void> {
    for (const item of DEFAULT_CONFIGURATION) {
      await this.database(
        `
        INSERT INTO configuration (key, value)
        VALUES ($1, $2)
        ON CONFLICT (key) DO NOTHING
        `,
        [item.key, item.value],
      );
    }
  }

  private async upsertMetricValues(
    historyId: number,
    metrics: MetricValueMap,
    createdAt: string,
  ): Promise<void> {
    const values: string[] = [];
    const params: Array<number | string | null> = [];
    let paramIndex = 1;

    for (const metricKey of SUPPORTED_METRIC_KEYS) {
      values.push(`($${paramIndex}, $${paramIndex + 1}, $${paramIndex + 2}, $${paramIndex + 3})`);
      params.push(historyId, metricKey, metrics[metricKey], createdAt);
      paramIndex += 4;
    }

    await this.database(
      `
      INSERT INTO etf_metrics (history_id, metric_key, metric_value, created_at)
      VALUES ${values.join(', ')}
      ON CONFLICT(history_id, metric_key) DO UPDATE SET
          metric_value = excluded.metric_value,
          created_at = excluded.created_at
      `,
      params,
    );
  }

  private mapHistoryMetricRows(rows: EtfHistoryMetricJoinRow[]): EtfHistoryRow[] {
    const historyById = new Map<number, EtfHistoryRow>();

    for (const row of rows) {
      const historyId = Number(row.id);
      if (!Number.isFinite(historyId)) {
        continue;
      }

      let historyRow = historyById.get(historyId);
      if (!historyRow) {
        historyRow = {
          id: historyId,
          symbol: row.symbol,
          report_date: row.report_date,
          units_in_circulation: null,
          vuan: null,
          net_assets: null,
          report_url: row.report_url,
          created_at: row.created_at,
        };
        historyById.set(historyId, historyRow);
      }

      if (typeof row.metric_key === 'string' && this.isMetricKey(row.metric_key)) {
        historyRow[row.metric_key] = row.metric_value;
      }
    }

    return Array.from(historyById.values());
  }

  private createEmptyMetricValueMap(): MetricValueMap {
    const values = {} as MetricValueMap;
    for (const metricKey of SUPPORTED_METRIC_KEYS) {
      values[metricKey] = null;
    }

    return values;
  }

  private isMetricKey(value: string): value is MetricKey {
    return METRIC_KEY_SET.has(value);
  }
}
